### ISSUE TITLE
spacestatus script „bounces“ when status opens

### ISSUE THREAD

**Issue by H3wastooshort** [vspaceone/spaceinfo-scripts#1]
when closing the space, everything works fine, but ehen opening the script turns the monitor on and off randomly snd rapidly about 5 times. end state unknown

**Comment by H3wastooshort** [comment]
Issue found: the space status switch bounces, sending multiple on/off messages, some of wich go missing. Not an issue with my spaghetti code.

**Comment by noppelmax** [comment]
thanks for investigating! :) We should 'debounce' the switch. :D
